apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-monitor
  namespace: default
roleRef:
  kind: ClusterRole
  name: monitoring-endpoints
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: admin-monitor
  apiGroup: rbac.authorization.k8s.io
