apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: rbac.authorization.k8s.io
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
  