apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-deployment
  name: nginx-deployment
spec:
  containers:
  - image: nginx:1.8
    name: nginx-deployment
    resources: {}
    ports: 
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
