apiVersion: v1
kind: Pod
metadata:
  name: happyelephant
  namespace: mynamespace
  labels: 
    app: jenkins
    department: mywork
    company: mycompany 
spec:
  containers:
  - name: jenkins
    image: jenkins:2.13.0
    ports:
    - name: jenkinsport
      containerPort: 8080