apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring
  namespace: default
aggregationRule:
  clusterRoleSelectors:
  - matchLabels: 
    rbac.example.com/aggregate-to-monitoring: "true"
rules: []      