apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-5
spec:
  containers:
  - name: security-context-demo-5
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      seLinuxOptions:
        level: "s0:c123,c456"
