apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: security-context-demo
  name: security-context-demo
spec:
  volumes:
  - name: security-context-volume
    emptyDir: {}
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers:
  - image: busybox
    name: security-context-demo
    resources: {}
    command: ["sh", "-c", "sleep 1h"]
    volumeMounts:
    - name: security-context-volume
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
