#application/guestbook/frontend-deployment.yaml 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80

---
#frontend-service
apiVersion: v1
kind: Service
metadata:
  name: frontend1
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer 
  ports:
  - name: frontend-port
    port: 80
    targetPort: 8080
  selector:
    app: guestbook
    tier: frontend