apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels: 
    app: nginx
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: my-volume1
      mountPath: "etc/foo"
      readOnly: true
  volumes:
  - name: my-volume1
    secret:
      secretName: my-secret2
      items:
      - key: username
        path: "my-group/my-username"
        mode: 511
        key: password
        path: "my-group/password"
        mode: 511

