apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-01-15T08:53:27Z"
  generation: 2
  name: backend-deployment
  namespace: default
  resourceVersion: "175920"
  selfLink: /apis/apps/v1/namespaces/default/deployments/backend-deployment
  uid: 82532aa2-59bc-4d51-bce8-e368ffd3bdf9
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        tier: backend
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: backend-nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
#dedicated=special-user:NoSchedule
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "special-user"
        effect: "NoSchedule"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-01-15T08:53:27Z"
    lastUpdateTime: "2020-01-15T08:53:34Z"
    message: ReplicaSet "backend-deployment-fc58bbc67" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-21T04:11:12Z"
    lastUpdateTime: "2020-01-21T04:11:12Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 3
  unavailableReplicas: 2
  updatedReplicas: 3
